# General Configuration
dataset:
  name: "Sri_Lankan"    # Options: "Oral_Cancer", "Oral_Cancer_2.0", "Sri_Lankan"
  image_size: [224, 224] # Specify image size (height, width)
  batch_size: 8
  num_classes: 4         # OPMD, Benign, Healthy, OCA (update if more classes)
  
model:
  name: "MobileNetV2"      # Options: "EfficientNetB0", "MobileNetV2", "ResNet50", "InceptionV3"
  weights: "imagenet"         # Use "imagenet" for pre-trained weights, or "None" for random initialization
  trainable: False            # Set to True for fine-tuning the base model

# Dataset Paths
paths:
  Sri_Lankan:
    images_dir: "data/Sri_Lankan_Dataset/Images"
    annotations_file: "data/Sri_Lankan_Dataset/Imagewise_Data (2).csv"


# Training Configuration
training:
  learning_rate: 0.001
  epochs: 20
  optimizer: "adam"       # Options: "adam", "sgd", "rmsprop"
  loss_function: "sparse_categorical_crossentropy"
  metrics: ["sparse_categorical_accuracy"]
